insert into ENDERECO (ID, BAIRRO, CIDADE, LOGRADOURO, NUMERO, UF) VALUES ('1','JARDIM PAQUETA', 'BELO HORIZONTE', 'RUA SUSANA MARIA', '13', 'MG');
insert into ENDERECO (ID, BAIRRO, CIDADE, LOGRADOURO, NUMERO, UF) VALUES ('2','OURO PRETO', 'BELO HORIZONTE', 'RUA PAULA MOTA', '120', 'MG');
insert into ENDERECO (ID, BAIRRO, CIDADE, LOGRADOURO, NUMERO, UF) VALUES ('3','CASTELO', 'BELO HORIZONTE', 'AVENIDA BARCELLOS', '20', 'MG');
insert into RESTAURANTE (CNPJ, NOME, ID_ENDERECO) VALUES ('123','TESTE DE RESTAURANTE 1', '1');
insert into RESTAURANTE (CNPJ, NOME, ID_ENDERECO) VALUES ('456','TESTE DE RESTAURANTE 2', '2');
insert into RESTAURANTE (CNPJ, NOME, ID_ENDERECO) VALUES ('789','TESTE DE RESTAURANTE 3', '3');